module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URL: 'http://139.59.76.223/anytimedoc/api/',
    home :'home',
    Signin :'Signin',
    Signup :'Signup',
    guid:'',
    muid:'',
    youtubekey:'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    is_yt:0,
    newsWhich:'',
    newsImage:'',
    newsTitle:'',
    appointment:[],
    profile:'',
    front_main :'front_main',
    industry :'',
    categoryID : '',
    array :[],
    userID:'',
    profile :'',
    token: '',
    productname : '',
    username: '',
    gender: '',
    email: '',
    password: '',
    otps: '',
    dob: '',



    related:'',
    productid: '',
    cartId :'',
    myid :'',
    video:'',
    newsid :'',
    derive_category :'derive_category',
    derive_detail_category : 'derive_detail_category',
    info_number :'',
    info_email : '',
    mainid : '',
    user_id:'1',
    dervie_detail_of_product : 'dervie_detail_of_product',
    userInfo :[],
    myname :'',
    mymobile :'',
    lat:"28.70937000",
    long:"77.12312000",
    bookingArray :[],
    doctor_condition:'online',

    referal :'',
    apply_to:'',
    groupName :'',
    groupId :'',
    groupImage:'',
    profileImage:'',
    editGroup:'',
    myemail :'',
    myusername:'',
    mymobile :'',
    is_refer_verify:'',
   referral_code :'',

    mypassword :'',
    mydeviceID :'',
    mydeviceType :'',
    mydeviceToken :'',
    mymodel_name :'',
    mycarrier_name :'',
    mydevice_country :'',
    mydevice_memory :'',
    otps :'',
    fmobile :'',
    isScreen :'',
    isScreen :'',
    type :'',
    keyword:'',
    author_id :'',
    author :'',
    another:'',
    comment_id:'',
    post_id:'',
    wallets:'',
    anotherUsername:'',
    commentFlagId:'',
    need_help:'need_help',
    COLOR: {
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',
    },
};